### ISSUE TITLE
Outdated or broken link?

### ISSUE THREAD

**Issue by mgiugliano** [LibreDMR/OpenGD77_UserGuide#66]
The link to download the OpenGD77 CPS software, https://www.opengd77.com/downloads/CPS/Latest, is broken.

I even get a security alert from the browser.  

The correct link should be 
https://www.opengd77.com/downloads/PC_CPS_20230910/Latest/

However, now the zip file requires a password (which is the release number)

P.S. Why the GD77 project is NOT on GitHub? The website/forum/repository is really a pain in the neck to make sense of. I spent 1h to reconstruct all the above information. This is NOT user friendly. Why is the Open GD77 community not "open" :( ?

**Comment by rogerclarkmelbourne** [comment]
The OpenGD77 firmware and CPS was removed from github becasue of legal issues

The link to the download will need to be removed from the User Guide, because we constantly have to move where we store the CPS because someone keeps reporting the CPS a virus and it then gets blocked by Google Safe browsing

The old link is actually now to an empty folder but once Google blocks a URL there is no way to unblock it, even by removing the files. Google do not have a way to flag false reports of viruses, especially as a few antivirus have false positive reports of the CPS being a virus or suspicuious
The problem is that its not signed with a secuirty certificate, and then most antivirus err on assuming is potentially a virus, certificates cost hundreds of dollars per year and this project is non-commercial, so has no funds.

**Comment by rogerclarkmelbourne** [comment]
Fixed. Link is now to the CPS section of the forum
