### ISSUE TITLE
Trainplotter in oppenGD77 

### ISSUE THREAD

**Issue by Kukisman** [LibreDMR/OpenGD77_UserGuide#74]
Hello from Spain. 

I would like to add code for oppenGD77.

My intention is add a application like trainplotter to my retevis R3TS.

I need to transcript analogue code to ASCI more or less.

https://www.coaa.co.uk/trainplotter.htm

Can you help me with a repository in GitHub? 

Please

**Comment by rogerclarkmelbourne** [comment]
This is not the correct place to post questions about the firware, this is the repo for the User Guide

The user support forum is

https://www.opengd77.com

Firmware source code release is documented here

https://www.opengd77.com/viewtopic.php?f=19&t=2742

However the firmware does not support any decoding of FM signals by the MCU, because it's not know even if there is a hardware signal connection from the FM Rx audio to the MCU on the RT-3S.
And there are no published schematics for that radio, or the Radioddity GD-77
